import re

with open('frontend/src/pages/FluxoCaixa.jsx', 'r', encoding='utf-8') as f:
    content = f.read()

fixes = [
    ('LanÃ§amentos', 'Lançamentos'),
    ('lanÃ§amentos', 'lançamentos'),
    ('lanÃ§amento', 'lançamento'),
    ('LanÃ§amento', 'Lançamento'),
    ('ConciliaÃ§Ã£o', 'Conciliação'),
    ('conciliaÃ§Ã£o', 'conciliação'),
    ('ConciliaÃ§Ã£o', 'Conciliação'),
    ('DescriÃ§Ã£o', 'Descrição'),
    ('descriÃ§Ã£o', 'descrição'),
    ('DescrÃ§Ã£o', 'Descrição'),
    ('AÃ§Ã£o', 'Ação'),
    ('AÃ§Ãµes', 'Ações'),
    ('aÃ§Ã£o', 'ação'),
    ('aÃ§Ãµes', 'ações'),
    ('MarÃ§o', 'Março'),
    ('marÃ§o', 'março'),
    ('OperaÃ§Ã£o', 'Operação'),
    ('operaÃ§Ã£o', 'operação'),
    ('AtualizaÃ§Ã£o', 'Atualização'),
    ('atualizaÃ§Ã£o', 'atualização'),
    ('VisualizaÃ§Ã£o', 'Visualização'),
    ('visualizaÃ§Ã£o', 'visualização'),
    ('ComposiÃ§Ã£o', 'Composição'),
    ('composiÃ§Ã£o', 'composição'),
    ('PrevisÃ£o', 'Previsão'),
    ('previsÃ£o', 'previsão'),
    ('RealizaÃ§Ã£o', 'Realização'),
    ('realizaÃ§Ã£o', 'realização'),
    ('IntegraÃ§Ã£o', 'Integração'),
    ('integraÃ§Ã£o', 'integração'),
    ('ConfiguraÃ§Ã£o', 'Configuração'),
    ('configuraÃ§Ã£o', 'configuração'),
    ('opÃ§Ã£o', 'opção'),
    ('OpÃ§Ã£o', 'Opção'),
    ('opÃ§Ãµes', 'opções'),
    ('OpÃ§Ãµes', 'Opções'),
    ('perÃ­odo', 'período'),
    ('PerÃ­odo', 'Período'),
    ('Ã©', 'é'),
    ('Ã¡', 'á'),
    ('Ã³', 'ó'),
    ('Ãº', 'ú'),
    ('Ã­', 'í'),
    ('Ã£', 'ã'),
    ('Ã§', 'ç'),
    ('Ãµ', 'õ'),
    ('Ã¢', 'â'),
    ('Ãª', 'ê'),
    ('Ã´', 'ô'),
    ('Ã ', 'à'),
    ('Ã‡', 'Ç'),
    ('Ã‰', 'É'),
    ('Ã"', 'Ó'),
    ('Ã', 'Á'),
    ('Ãš', 'Ú'),
    ('Ã"', 'Ô'),
    ('Â·', '·'),
    ('â€"', '—'),
    ('â€¢', '•'),
    ("â€™", "'"),
    ('clique em Ã¢oe', 'clique em ✏'),
    ('clique em âoe', 'clique em ✏'),
    ('previsto Ã—', 'previsto ×'),
    ('Ã—', '×'),
    ('Ã\x83', 'Ã'),
]

for wrong, right in fixes:
    content = content.replace(wrong, right)

with open('frontend/src/pages/FluxoCaixa.jsx', 'w', encoding='utf-8') as f:
    f.write(content)

print('Concluído!')
